name: Build via SPEC

on: [push, workflow_dispatch]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with SPEC (Windows)
        run: |
          pyinstaller build_windows.spec
          ls -R dist  # Проверка содержимого

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-application
          path: |
            dist/ImageAnnotationTool.exe
            dist/ImageAnnotationTool/*
  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name ImageAnnotation your_script.py

      - name: Remove macOS quarantine
        run: |
          xattr -r -d com.apple.quarantine dist/ImageAnnotation.app

      - name: Create DMG
        run: |
          brew install create-dmg || true
          create-dmg \
            --volname "ImageAnnotation" \
            --window-pos 200 120 \
            --window-size 600 300 \
            --icon-size 100 \
            --icon "ImageAnnotation.app" 150 150 \
            --hide-extension "ImageAnnotation.app" \
            --app-drop-link 450 150 \
            "ImageAnnotation.dmg" \
            "dist/ImageAnnotation.app"

      - name: Notarize (optional)
        if: false # Установите true если есть Apple Developer ID
        env:
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        run: |
          xcrun altool --notarize-app \
            --primary-bundle-id "com.yourcompany.ImageAnnotation" \
            --username "$APPLE_ID" \
            --password "$APPLE_PASSWORD" \
            --file "ImageAnnotation.dmg"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageAnnotation-MacOS
          path: |
            dist/ImageAnnotation.app
            ImageAnnotation.dmg