name: Build via SPEC

on: [push, workflow_dispatch]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with SPEC (Windows)
        run: |
          pyinstaller build_windows.spec
          ls -R dist  # Проверка содержимого

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-application
          path: |
            dist/ImageAnnotationTool.exe
            dist/ImageAnnotationTool/*
  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with SPEC
        run: |
          pyinstaller build_mac.spec
          ls -R dist

      - name: Remove quarantine
        run: |
          xattr -r -d com.apple.quarantine dist/ImageAnnotation.app

      - name: Ad-hoc codesign
        run: |
          codesign --force --deep --sign - dist/ImageAnnotation.app

      - name: Create DMG
        run: |
          create-dmg \
            --volname "ImageAnnotation" \
            --background "background.png" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --icon "ImageAnnotation.app" 150 190 \
            --app-drop-link 450 190 \
            "ImageAnnotation.dmg" \
            "dist/ImageAnnotation.app"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MacOS-Build
          path: |
            dist/ImageAnnotation.app
            ImageAnnotation.dmg
