name: Cross-Platform Build

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build application
        run: |
          # Запуск PyInstaller
          pyinstaller build.spec

      - name: Prepare artifacts
        run: |
          # Упаковываем результаты
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            cd dist
            zip -r ImageAnnotation-macOS.zip ImageAnnotation.app
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            cd dist
            7z a ImageAnnotation-Windows.zip ImageAnnotation.exe
          else
            cd dist
            tar czf ImageAnnotation-Linux.tar.gz ImageAnnotation
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-Build
          path: |
            dist/*.zip
            dist/*.tar.gz
            dist/*.app/**  # Для macOS

      - name: Create Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ImageAnnotation*.zip
            dist/ImageAnnotation*.tar.gz
            dist/*.app/**  # Для macOS