name: Cross-Platform Build

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build application
        run: |
          pyinstaller build.spec

      - name: Package artifacts
        run: |
          cd dist
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "Packaging macOS app..."
            if [[ -d "ImageAnnotation.app" ]]; then
              # Упаковать всю .app в zip
              ditto -c -k --sequesterRsrc --keepParent ImageAnnotation.app ImageAnnotation-macOS.zip
            else
              echo "::error::macOS app bundle not found!"
              exit 1
            fi
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "Packaging Windows app..."
            if [[ -d "ImageAnnotation" ]]; then
              powershell Compress-Archive -Path ImageAnnotation -DestinationPath ImageAnnotation-Windows.zip
            else
              echo "::error::Windows folder not found!"
              exit 1
            fi
          else
            echo "Packaging Linux app..."
            if [[ -d "ImageAnnotation" ]]; then
              tar czf ImageAnnotation-Linux.tar.gz ImageAnnotation
            else
              echo "::error::Linux folder not found!"
              exit 1
            fi
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-Build
          path: |
            dist/*.zip
            dist/*.tar.gz

      - name: Create Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
            dist/*.tar.gz
