name: Cross-Platform App Build

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build application (with splash)
        run: bash package_app.sh

      - name: List final app contents
        run: |
          echo "::group::dist/final/"
          ls -R dist/final || true
          echo "::endgroup::"

      - name: Package final .app
        run: |
          cd dist/final
          ditto -c -k --sequesterRsrc --keepParent ImageAnnotation.app ImageAnnotation-macOS.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageAnnotation-macOS
          path: dist/final/ImageAnnotation-macOS.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build application (with splash)
        run: bash package_app.sh
        shell: bash

      - name: List windows app contents
        run: |
          echo "::group::dist/windows/"
          ls -R dist/windows || true
          echo "::endgroup::"
        shell: bash

      - name: Package windows app
        run: |
          cd dist/windows
          powershell Compress-Archive -Path ImageAnnotation.exe,ImageAnnotationMain.exe -DestinationPath ImageAnnotation-windows.zip
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageAnnotation-windows
          path: dist/windows/ImageAnnotation-windows.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build application (with splash)
        run: bash package_app.sh
        shell: bash

      - name: List linux app contents
        run: |
          echo "::group::dist/linux/"
          ls -R dist/linux || true
          echo "::endgroup::"
        shell: bash

      - name: Package linux app
        run: |
          cd dist/linux
          zip ImageAnnotation-linux.zip ImageAnnotation ImageAnnotationMain
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ImageAnnotation-linux
          path: dist/linux/ImageAnnotation-linux.zip
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows, build-linux]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: ImageAnnotation-macOS
          path: release

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: ImageAnnotation-windows
          path: release

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: ImageAnnotation-linux
          path: release

      - name: List release files
        run: ls -lh release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/ImageAnnotation-macOS.zip
            release/ImageAnnotation-windows.zip
            release/ImageAnnotation-linux.zip
