name: Cross-Platform Build

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build application
        run: |
          # Запуск PyInstaller
          pyinstaller build.spec

      - name: Package artifacts
        run: |
          cd dist
          if [ "$RUNNER_OS" == "macOS" ]; then
            echo "Packaging macOS app..."
            if [ -d "ImageAnnotation.app" ]; then
              zip -r ImageAnnotation-macOS.zip ImageAnnotation.app
            else
              echo "::error::macOS app bundle not found!"
              exit 1
            fi
          elif [ "$RUNNER_OS" == "Windows" ]; then
            echo "Packaging Windows app..."
            if [ -f "ImageAnnotation.exe" ]; then
              powershell -command "Compress-Archive -Path ImageAnnotation.exe -DestinationPath ImageAnnotation-Windows.zip"
            else
              echo "::error::Windows executable not found!"
              exit 1
            fi
          else
            echo "Packaging Linux app..."
            if [ -f "ImageAnnotation" ]; then
              tar czf ImageAnnotation-Linux.tar.gz ImageAnnotation
            else
              echo "::error::Linux executable not found!"
              exit 1
            fi
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-Build
          path: |
            dist/*.zip
            dist/*.tar.gz
            dist/*.app/**  # Для macOS

      - name: Create Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/ImageAnnotation*.zip
            dist/ImageAnnotation*.tar.gz
            dist/*.app/**  # Для macOS