name: Cross-Platform Build

on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build application
        run: pyinstaller build.spec

      - name: List dist contents
        run: |
          echo "::group::dist/"
          ls -R dist || true
          echo "::endgroup::"

      - name: Package artifacts
        run: |
          cd dist

          if [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "Packaging for macOS..."
            if [[ -d "ImageAnnotation.app" ]]; then
              ditto -c -k --sequesterRsrc --keepParent ImageAnnotation.app ImageAnnotation-macOS.zip
            else
              echo "⚠️ ImageAnnotation.app not found"
            fi

          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            echo "Packaging for Windows..."
            if compgen -G "ImageAnnotation*.exe" > /dev/null; then
              echo "Found EXE, zipping..."
              powershell Compress-Archive -Path ImageAnnotation*.exe -DestinationPath ImageAnnotation-Windows.zip
            elif [[ -d "ImageAnnotation" ]]; then
              echo "Found folder, zipping..."
              powershell Compress-Archive -Path ImageAnnotation -DestinationPath ImageAnnotation-Windows.zip
            else
              echo "⚠️ No .exe or folder found"
            fi

          elif [[ "$RUNNER_OS" == "Linux" ]]; then
            echo "Packaging for Linux..."
            if [[ -d "ImageAnnotation" ]]; then
              tar czf ImageAnnotation-Linux.tar.gz ImageAnnotation
            elif compgen -G "ImageAnnotation*" > /dev/null; then
              tar czf ImageAnnotation-Linux.tar.gz ImageAnnotation*
            else
              echo "⚠️ Nothing found to package"
            fi
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-Build
          path: |
            dist/*.zip
            dist/*.tar.gz

      - name: Create Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.zip
            dist/*.tar.gz
